set(BUILDENGINE_TOOLS_CMAKE_SRC_DIR "${BUILDENGINE_TOOLS_CMAKE_SRC_DIR}" PARENT_SCOPE)
set(BUILDENGINE_SCRIPTS_CMAKE_DIR "${BUILDENGINE_SCRIPTS_CMAKE_DIR}" PARENT_SCOPE)
set(ENV_CMAKE_COMMAND ${ENV_CMAKE_COMMAND} PARENT_SCOPE)
set(ENV_CMAKE_SILENT_COMMAND ${ENV_CMAKE_SILENT_COMMAND} PARENT_SCOPE)