set(BUILDENGINE_TOOLS_GIT_SRC_DIR "${BUILDENGINE_TOOLS_GIT_SRC_DIR}" PARENT_SCOPE)
set(BUILDENGINE_SCRIPTS_GIT_DIR "${BUILDENGINE_SCRIPTS_GIT_DIR}" PARENT_SCOPE)
set(ENV_GIT_COMMAND ${ENV_GIT_COMMAND} PARENT_SCOPE)