set(BUILDENGINE_ENV_DIR "${BUILDENGINE_ENV_DIR}" PARENT_SCOPE)
set(BUILDENGINE_SCRIPTS_ENV_DIR "${BUILDENGINE_SCRIPTS_ENV_DIR}" PARENT_SCOPE)
set(ENV_RUNNER ${ENV_RUNNER} PARENT_SCOPE)
set(ENV_RUNNER_SILENT ${ENV_RUNNER_SILENT} PARENT_SCOPE)